# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f1c419bb8c0330f2075ded5ce966186f984f49dcf9beb03efa288f0d543035da8a7378a158fa1d299d74407409a031737bd8bc59b3479d8b59b75ba27e89a51

test:
  secret_key_base: bb6d9938dcc60c657c3ae0fa9b6a2754ed0e838b2e6e88306db9e8296442492369c2e7c9625e3d3f416abb8f5eb87c2682f5e462817902b94da550be7e48bd3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
